In [9]:
import torch
import torch.nn as nn
from utils import make_var, count_non_zero_length

In [6]:
tmp = make_var(['Tiras', 'Ann', 'El'])
tmp

tensor([[116, 105, 114,  97, 115],
        [ 97, 110, 110,   0,   0],
        [101, 108,   0,   0,   0]])

In [7]:
lengths = count_non_zero_length(tmp)
lengths

[5, 3, 2]

In [10]:
emb = nn.Embedding(128, 5)
embedding = emb(tmp)
embedding

tensor([[[-0.3121, -1.2949,  0.5441,  1.4017,  1.3755],
         [ 0.4428, -1.3781,  0.5764,  0.5932,  0.0759],
         [ 0.0866,  0.6813,  0.6346, -0.5444, -0.1464],
         [ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
         [ 0.6739,  1.1161,  0.8071,  0.6277,  1.5795]],

        [[ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
         [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
         [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
         [ 0.9047,  0.0991, -0.5803, -1.0122,  0.3395],
         [ 0.9047,  0.0991, -0.5803, -1.0122,  0.3395]],

        [[ 2.7781, -0.3865,  0.7516, -1.0276, -1.7625],
         [ 1.2809,  2.2759, -0.3402, -0.5154, -0.1789],
         [ 0.9047,  0.0991, -0.5803, -1.0122,  0.3395],
         [ 0.9047,  0.0991, -0.5803, -1.0122,  0.3395],
         [ 0.9047,  0.0991, -0.5803, -1.0122,  0.3395]]],
       grad_fn=<EmbeddingBackward>)

In [11]:
embedding.size()

torch.Size([3, 5, 5])

In [12]:
from pprint import pprint

pps_in = torch.nn.utils.rnn.pack_padded_sequence(embedding, batch_first=True, lengths=lengths)
pps_in

PackedSequence(data=tensor([[-0.3121, -1.2949,  0.5441,  1.4017,  1.3755],
        [ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
        [ 2.7781, -0.3865,  0.7516, -1.0276, -1.7625],
        [ 0.4428, -1.3781,  0.5764,  0.5932,  0.0759],
        [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
        [ 1.2809,  2.2759, -0.3402, -0.5154, -0.1789],
        [ 0.0866,  0.6813,  0.6346, -0.5444, -0.1464],
        [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
        [ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
        [ 0.6739,  1.1161,  0.8071,  0.6277,  1.5795]],
       grad_fn=<PackPaddedSequenceBackward>), batch_sizes=tensor([3, 3, 2, 1, 1]))

In [13]:
pps_out = torch.nn.utils.rnn.pad_packed_sequence(pps_in, batch_first=True)
pps_out

(tensor([[[-0.3121, -1.2949,  0.5441,  1.4017,  1.3755],
          [ 0.4428, -1.3781,  0.5764,  0.5932,  0.0759],
          [ 0.0866,  0.6813,  0.6346, -0.5444, -0.1464],
          [ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
          [ 0.6739,  1.1161,  0.8071,  0.6277,  1.5795]],
 
         [[ 0.7184, -1.0451, -0.3598,  0.5787,  2.1200],
          [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
          [ 0.6572, -0.4241, -0.4780, -0.7486,  0.3145],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[ 2.7781, -0.3865,  0.7516, -1.0276, -1.7625],
          [ 1.2809,  2.2759, -0.3402, -0.5154, -0.1789],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]],
        grad_fn=<TransposeBackward0>), tensor([5, 3, 2]))

In [14]:
gru = nn.GRU(5, 18, 2)

In [16]:
pps_out_n_size, ht = gru(pps_in)

In [17]:
result = torch.nn.utils.rnn.pad_packed_sequence(pps_out_n_size, batch_first=True)

In [18]:
result

(tensor([[[-0.0607,  0.0276,  0.0993, -0.0630,  0.0817, -0.0151, -0.0366,
           -0.1371, -0.1705, -0.2021, -0.1702, -0.0793, -0.0649,  0.0172,
            0.1412, -0.0243,  0.0837, -0.1182],
          [-0.1265,  0.1196,  0.1243, -0.0662,  0.1252, -0.0631, -0.0749,
           -0.1220, -0.2660, -0.2579, -0.2908, -0.0925, -0.1134,  0.0116,
            0.1838, -0.0324,  0.1289, -0.2091],
          [-0.1068,  0.1429,  0.1316, -0.0299,  0.0923, -0.0988, -0.1194,
           -0.1528, -0.2565, -0.2595, -0.3208, -0.1507, -0.1309,  0.0385,
            0.2417,  0.0195,  0.2226, -0.2412],
          [-0.0709,  0.1387,  0.1148, -0.1062,  0.1147, -0.0644, -0.1817,
           -0.1731, -0.3509, -0.3192, -0.3689, -0.1816, -0.1366,  0.0979,
            0.3185, -0.0032,  0.1836, -0.3370],
          [ 0.0007,  0.1507,  0.0935, -0.1508,  0.1014, -0.1020, -0.2110,
           -0.2009, -0.4067, -0.3501, -0.3640, -0.1777, -0.1494,  0.1859,
            0.4027,  0.0273,  0.1590, -0.3921]],
 
         [[-0.029